// <auto-generated />
using GymExerciseClassLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymExerciseClassLibrary.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ExerciseTraining", b =>
                {
                    b.Property<int>("ExercisesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainingsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExercisesId", "TrainingsId");

                    b.HasIndex("TrainingsId");

                    b.ToTable("ExerciseTraining", (string)null);
                });

            modelBuilder.Entity("GymExerciseClassLibrary.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MachineName")
                        .HasColumnType("TEXT");

                    b.Property<int>("MusclegroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RepsGoal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Sets")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MusclegroupId");

                    b.ToTable("Exercises", (string)null);
                });

            modelBuilder.Entity("GymExerciseClassLibrary.Models.Musclegroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Musclegroups", (string)null);
                });

            modelBuilder.Entity("GymExerciseClassLibrary.Models.Repetition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Set")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("Repetitions", (string)null);
                });

            modelBuilder.Entity("GymExerciseClassLibrary.Models.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trainings", (string)null);
                });

            modelBuilder.Entity("ExerciseTraining", b =>
                {
                    b.HasOne("GymExerciseClassLibrary.Models.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymExerciseClassLibrary.Models.Training", null)
                        .WithMany()
                        .HasForeignKey("TrainingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymExerciseClassLibrary.Models.Exercise", b =>
                {
                    b.HasOne("GymExerciseClassLibrary.Models.Musclegroup", "Musclegroup")
                        .WithMany()
                        .HasForeignKey("MusclegroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musclegroup");
                });

            modelBuilder.Entity("GymExerciseClassLibrary.Models.Repetition", b =>
                {
                    b.HasOne("GymExerciseClassLibrary.Models.Exercise", null)
                        .WithMany("Reps")
                        .HasForeignKey("ExerciseId");
                });

            modelBuilder.Entity("GymExerciseClassLibrary.Models.Exercise", b =>
                {
                    b.Navigation("Reps");
                });
#pragma warning restore 612, 618
        }
    }
}
